### PR TITLE
master categories is selected with all categories for deletion

### PR DESCRIPTION
**Pull request by torvista**
and
sizeof->count
short array syntax
expand single line ifs to group as per PSR-2

comparison looks worse than it is.

### CODE REVIEW

**Comment by torvista** [comment]
any problem with this?

**Comment by scottcwilson** [comment]
I'm not the decider.  You need to submit a PR to zencart/zencart.

**Comment by torvista** [comment]
But this is your branch, so you need to submit it, no?
I'll do one if you prefer?

**Comment by scottcwilson** [comment]
You go ahead and do your own.   That will be easier.

**Pull request closed without merging**
